FROM node:16-alpine

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app

RUN yarn install

COPY . /app

RUN yarn build

# change user diferent to root

EXPOSE 3000

CMD [ "yarn", "start" ]

# docker build -tag tagName
# docker build -t nextjs-initial .
# docker run --name=next-app -p 3000:3000 nextjs-initial